spring:
  application:
    name: flipkart-user-admin-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 1000
        max-attempts: 6

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka




#server.port=8082
#
#spring.profiles.active=dev
#
#spring.config.import=optional:configserver:http://localhost:8888
#spring.cloud.config.fail-fast=true
#spring.cloud.config.retry.initial-interval=1000
#spring.cloud.config.retry.max-attempts=6
#
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka